export const INCREMENT_PLUS = 'INCREMENT_PLUS';

export const PRICE_INCREMENT_PLUS = 'PRICE_INCREMENT_PLUS';

export const PRODUCT_INCREMENT_PLUS = 'PRODUCT_INCREMENT_PLUS';

export const CUSTOM_STR = 'CUSTOM_STR';
